import type { PortfolioProject } from "@/types/content";

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: "jarvis-ai",
    title: "Jarvis AI",
    category: "AI Desktop Assistant",
    description: "A next-generation AI desktop assistant focused on intelligent automation, voice interaction, local execution, and productivity workflows.",
    technologies: ["Electron", "React", "Python", "OpenAI"],
    image: "/images/portfolio/jarvis-ai.jpg",
    colSpan: "featured",
    status: "In Development",
    liveUrl: "",
    buttonLabel: "Coming Soon",
  },
  {
    id: "wavex",
    title: "Wavex Music Streaming Platform",
    category: "Music Streaming",
    description: "A modern music streaming platform featuring seamless playback, playlist management, responsive design, and an immersive listening experience built with the MERN stack.",
    technologies: ["MongoDB", "Express", "React", "Node.js"],
    image: "/images/portfolio/wavex.jpg",
    colSpan: "half",
    status: "Beta",
    liveUrl: "https://wavex-mocha.vercel.app/",
    buttonLabel: "Live Demo",
  },
  {
    id: "personal-portfolio",
    title: "Personal Portfolio",
    category: "Web Portfolio",
    description: "My personal portfolio showcasing premium UI/UX, frontend engineering, responsive design, and modern web animations.",
    technologies: ["Next.js", "Tailwind CSS", "Framer Motion"],
    image: "/images/portfolio/personal-portfolio.jpg",
    colSpan: "half",
    status: "Live",
    liveUrl: "https://my-portfolio-eight-topaz-41.vercel.app/",
    buttonLabel: "Live Demo",
  },
  {
    id: "aura-commerce",
    title: "Aura Commerce",
    category: "Headless Storefront",
    description: "An e-commerce website built during my first year of engineering. A complete redesign is planned as part of CoreByte Studios.",
    technologies: ["Shopify Plus", "Next.js", "Framer Motion"],
    image: "/images/portfolio/aura.png",
    colSpan: "half",
    status: "Legacy Project",
    liveUrl: "",
    buttonLabel: "Coming Soon",
  },
];
